# -*- coding: utf-8 -*-
"""curso_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-xnKdk81IN0ZBWPUw8FTS76sbt5Ei_T7
"""

#importando a biblioteca Pandas
import pandas as pd

#df: data frame (no arquivo Gapminder tem uma linha com erro!)
df = pd.read_csv("/content/drive/MyDrive/Gapminder.csv", error_bad_lines=False, sep=";")

#visualizar as 5 primeiras linhas
df.head()

df = df.rename(columns={'country':'País', 'continent':'Continente', 'year':'Ano', 'lifeExp':'Exp Vida', 'pop':'População', 'gdpPercap':'PIB'})

df.head(10)

#total de linhas e colunas
df.shape

df.columns

df.dtypes

df.tail(3)

df.describe()

df['Continente'].unique()

#loc: fazer filtro na base de dados
oceania = df.loc[df['Continente'] == 'Oceania']

oceania.head()

oceania['Continente'].unique()

df.groupby("Continente")["País"].nunique()

df.groupby("Ano")["Exp Vida"].mean().head(10)

df["PIB"].mean()

df["PIB"].sum()